User.create!(:name => "brian", :email => "brian.joseff.14@dartmouth.edu", :password => "000000", :admin => true)
Plan.create!(:name => "Once-a-Week", :price => 5)
Plan.create!(:name => "Twice-a-Week", :price => 8)
Plan.create!(:name => "Once-a-Week + Bin Rental", :price => 8)
Plan.create!(:name => "Twice-a-Week + Bin Rental", :price => 11)
Building.create!(:name => "other")
Building.create!(:name => "19 E. Wheelock")
Building.create!(:name => "Alpha Chi Alpha")
Building.create!(:name => "Alpha Delta")
Building.create!(:name => "Amarna")
Building.create!(:name => "Andres")
Building.create!(:name => "Bildner")
Building.create!(:name => "Brown Hall")
Building.create!(:name => "Butterfield")
Building.create!(:name => "Channing Cox")
Building.create!(:name => "Chinese Language House")
Building.create!(:name => "Cohen")
Building.create!(:name => "Cutter Shabbaz")
Building.create!(:name => "Delta Delta Delta")
Building.create!(:name => "Epsilon Kappa Theta")
Building.create!(:name => "Foley")
Building.create!(:name => "French")
Building.create!(:name => "Gile")
Building.create!(:name => "Goldstein")
Building.create!(:name => "Hitchcock")
Building.create!(:name => "Kappa Delta Epsilon")
Building.create!(:name => "La Casa")
Building.create!(:name => "LALAC")
Building.create!(:name => "Lodge")
Building.create!(:name => "Lord")
Building.create!(:name => "Mid Mass")
Building.create!(:name => "North Mass")
Building.create!(:name => "South Mass")
Building.create!(:name => "Maxwell")
Building.create!(:name => "North Mass")
Building.create!(:name => "McCulloch")
Building.create!(:name => "McLane")
Building.create!(:name => "Mid Fay")
Building.create!(:name => "Morton")
Building.create!(:name => "Zimmerman")
Building.create!(:name => "Native American House")
Building.create!(:name => "New Hamp")
Building.create!(:name => "North")
Building.create!(:name => "North Fay")
Building.create!(:name => "Richardson")
Building.create!(:name => "Ripley")
Building.create!(:name => "Woodward")
Building.create!(:name => "Russell Sage")
Building.create!(:name => "Sigma Delt")
Building.create!(:name => "South Fay")
Building.create!(:name => "Streeter")
Building.create!(:name => "Topliff")
Building.create!(:name => "Wheeler")
Building.create!(:name => "Whittemore")